# Generated by Django 5.1.3 on 2024-11-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_category_remove_choice_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_option',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
